name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    name: test code base
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        # seperate code base into two versions
        go: ["stable"]
        # go: ["stable", "oldstable"]
    steps:
      - uses: actions/checkout@v4

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Vet
        run: go vet ./...

      - name: Tidy
        run: go mod tidy

      - name: Mod download
        run: go mod download

      - name: Mod verify
        run: go mod verify

      - name: Generate
        run: go generate ./... && git diff --exit-code

      - name: Build
        run: go build -o /dev/null ./...

      - name: Run repo tests
        run: go test ./... -v
