name: go-testing

on: push

jobs:
  testing:
    name: test code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Run repo tests
        run: go test ./... -v
